name: CI/CD Pipeline

on:
  push:
    branches:
      - '**' # Run for pushes to any branch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pull-requests: write
  checks: write

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    needs: test
    name: Build and Analyze
    uses: ./.github/workflows/build.yml
    secrets: inherit
